# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discount.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='discount.proto',
  package='discount',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x64iscount.proto\x12\x08\x64iscount\"/\n\x08\x44iscount\x12\x0b\n\x03pct\x18\x01 \x01(\x02\x12\x16\n\x0evalue_in_cents\x18\x02 \x01(\x05\"5\n\x10\x44iscountResquest\x12\x0e\n\x06userID\x18\x01 \x01(\x05\x12\x11\n\tproductID\x18\x02 \x01(\x05\x32J\n\x0f\x44iscountService\x12\x37\n\x03Get\x12\x1a.discount.DiscountResquest\x1a\x12.discount.Discount\"\x00\x62\x06proto3')
)




_DISCOUNT = _descriptor.Descriptor(
  name='Discount',
  full_name='discount.Discount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pct', full_name='discount.Discount.pct', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_in_cents', full_name='discount.Discount.value_in_cents', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=75,
)


_DISCOUNTRESQUEST = _descriptor.Descriptor(
  name='DiscountResquest',
  full_name='discount.DiscountResquest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userID', full_name='discount.DiscountResquest.userID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='productID', full_name='discount.DiscountResquest.productID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['Discount'] = _DISCOUNT
DESCRIPTOR.message_types_by_name['DiscountResquest'] = _DISCOUNTRESQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Discount = _reflection.GeneratedProtocolMessageType('Discount', (_message.Message,), dict(
  DESCRIPTOR = _DISCOUNT,
  __module__ = 'discount_pb2'
  # @@protoc_insertion_point(class_scope:discount.Discount)
  ))
_sym_db.RegisterMessage(Discount)

DiscountResquest = _reflection.GeneratedProtocolMessageType('DiscountResquest', (_message.Message,), dict(
  DESCRIPTOR = _DISCOUNTRESQUEST,
  __module__ = 'discount_pb2'
  # @@protoc_insertion_point(class_scope:discount.DiscountResquest)
  ))
_sym_db.RegisterMessage(DiscountResquest)



_DISCOUNTSERVICE = _descriptor.ServiceDescriptor(
  name='DiscountService',
  full_name='discount.DiscountService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=132,
  serialized_end=206,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='discount.DiscountService.Get',
    index=0,
    containing_service=None,
    input_type=_DISCOUNTRESQUEST,
    output_type=_DISCOUNT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISCOUNTSERVICE)

DESCRIPTOR.services_by_name['DiscountService'] = _DISCOUNTSERVICE

# @@protoc_insertion_point(module_scope)
