version: '2.1'

orbs:
  deploy: burdzand/deploy-secrets@dev:1.0

jobs:
  build: # name of your job
      machine: # executor type
        image: ubuntu-2004:202010-01
  publish:
    steps:
      - checkout
      - run: echo "AQUI 2"

workflows:
  main:
    jobs:
      - deploy/publish:
        executor: 
          testename: anderso-teste
      - publish