version: '2.1'
orbs:
  gh: circleci/github-cli@2.0

workflows:
  test-and-deploy:
    jobs:
      - gh/release:
          filters:
            branches:
              only:
                - main
          notes-file: changelog.md
          tag: 1.1.0
          title: The initial release
