version: '2.1'

orbs:
  deploy: burdzand/deploy-secrets@dev:2.0

jobs:
  publish: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: echo "AQUI 2"

workflows:
  main:
    jobs:
      - deploy/publish
      - publish