version: '2.1'

orbs:
  deploy: burdzand/deploy-secrets@dev:4.0

jobs:
  publish:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run: echo "AQUI 4"

workflows:
  main:
    jobs:
      - deploy/publish:
          testename: anderson-ts-as
      - publish